server.port=${PORT:8082}

spring.datasource.url=${DB_URL:jdbc:postgresql://db.qxexfywslxqkuqrfhijk.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:22B1NUM2341a}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

soap.service.url=${SOAP_SERVICE_URL:http://localhost:8081/ws}